pipeline {
    agent any
    
    stages {
        stage('Checkout') {
    		steps {
        		checkout([
            			$class: 'GitSCM',
            			branches: [[name: '*/main']],
            			userRemoteConfigs: [[
                			url: 'https://github.com/Nyi-sudo/devops-local-cicd.git',
                			credentialsId: 'github-creds'
            				]]
        			])
    			}
		}	


        stage('Install Dependencies') {
            steps {
                sh 'chmod +x scripts/build.sh'
                sh './scripts/build.sh'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t local-devops-app .'
            }
        }

        stage('Deploy') {
            steps {
                sh 'chmod +x scripts/deploy.sh'
                sh './scripts/deploy.sh'
            }
        }
    }
}

